// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUEFSBNjoDJu4ZEpxBtUsC35qNmRPtXVM',
    appId: '1:63283700379:web:2de929dc4a2f192f7b9c3e',
    messagingSenderId: '63283700379',
    projectId: 'loginauth-1ff68',
    authDomain: 'loginauth-1ff68.firebaseapp.com',
    storageBucket: 'loginauth-1ff68.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJtzwCepFDWaKliGFIP6xoPUJEawL2Xow',
    appId: '1:63283700379:android:ab232ecf98c53c4f7b9c3e',
    messagingSenderId: '63283700379',
    projectId: 'loginauth-1ff68',
    storageBucket: 'loginauth-1ff68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBX_uD-4bOtxbRDIrw2XL4xrDfbRmVmUM',
    appId: '1:63283700379:ios:5d348db28d7071367b9c3e',
    messagingSenderId: '63283700379',
    projectId: 'loginauth-1ff68',
    storageBucket: 'loginauth-1ff68.appspot.com',
    iosBundleId: 'com.example.loginauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBX_uD-4bOtxbRDIrw2XL4xrDfbRmVmUM',
    appId: '1:63283700379:ios:5d348db28d7071367b9c3e',
    messagingSenderId: '63283700379',
    projectId: 'loginauth-1ff68',
    storageBucket: 'loginauth-1ff68.appspot.com',
    iosBundleId: 'com.example.loginauth',
  );
}
